services:
  api:
    build: ./backend
    container_name: shortener-backend
    ports:
      - "${API_PORT:-8000}:8000"
    env_file:
      - .env
    restart: always
    depends_on:
      - db
  web:
    build: ./frontend
    container_name: shortener-frontend
    ports:
      - '${WEB_PORT:-80}:80'
    depends_on:
      - api
  db:
    image: postgres:17
    restart: always
    container_name: shortener-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes: ["pgdata:/var/lib/postgresql/data"]
    ports:
      - "5423:5432"
volumes:
  pgdata:
